project:
  type: website
  output-dir: _site

website:
  title: "iv-image"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bootstrap.md
        text: Bootstrap
      - href: building.md
        text: Maintaining
      - href: consuming.md
        text: Consuming
      - href: tailnet.md
        text: Tailnet
      - href: registry.md
        text: Registry
